#git clone https://github.com/Tencent/ncnn.git
cd ncnn

cmake -Bbuild_host \
 -DCMAKE_BUILD_TYPE_INIT=Debug \
 -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
 -DCMAKE_C_COMPILER_WORKS=ON \
 -DCMAKE_CXX_COMPILER_WORKS=ON \
 -DNCNN_BUILD_TOOLS=OFF \
 -DNCNN_BUILD_EXAMPLES=OFF \
 -DNCNN_BUILD_BENCHMARK=OFF \
 -DNCNN_AVX=OFF \
 -DNCNN_AVX2=OFF \
 -DNCNN_SSE2=OFF \
 -DNCNN_RUNTIME_CPU=OFF \
 -DNCNN_THREADS=OFF \
 -DNCNN_OPENMP=OFF \
 -DNCNN_XOP=OFF \
 -DNCNN_PIXEL_AFFINE=OFF \
 -DNCNN_INSTALL_SDK=ON

cmake --build build_host --target install